### ISSUE TITLE
simplify_model.py script has broken links

### ISSUE THREAD

**Issue by rahul-dev-app** [CarkusL/CenterPoint#25]
Hi, when I run the simplify_model.py script it results in a broken graph for pfe_sim.onnx, when seen on netron. Please refer to the image attached.

![model_broken](https://github.com/CarkusL/CenterPoint/assets/76084774/1ffdb065-0463-42cd-b6c8-d5fa8d8424aa)

Output log for: export_pointpillars_onnx.py

```
workspace/Tracking/CenterPoint/det3d/core/bbox/geometry.py:149: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit(nopython=False)
workspace/Tracking/CenterPoint/det3d/core/bbox/geometry.py:162: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit(nopython=False)
workspace/Tracking/CenterPoint/det3d/core/bbox/geometry.py:280: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def points_in_convex_polygon_jit(points, polygon, clockwise=True):
2023-08-08 16:01:49.883573: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-08 16:01:50.013546: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-08-08 16:01:50.689251: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-08-08 16:01:50.689325: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/python3.8/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-08-08 16:01:50.689335: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
No Tensorflow
Object type:  PointPillars
Object type:  PillarFeatureNet
Object type:  PointPillarsScatter
Object type:  RPN
Object type:  CenterHead
Use HM Bias:  -2.19
Object type:  NuScenesDataset
Object type:  LoadPointCloudFromFile
Object type:  LoadPointCloudAnnotations
Object type:  Preprocess
Object type:  Voxelization
Object type:  AssignLabel
Object type:  Reformat
10
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Done
```

Output for: simplify_model.py

`Done`

Please help!

**Comment by CarkusL** [comment]
https://github.com/CarkusL/CenterPoint/blob/5912fab43dfe012112eb689a5a70d39c6bdf2654/tools/simplify_model.py#L30
you can change the 'input.1' in L30 to the input node name of the first Conv

**Comment by rahul-dev-app** [comment]
That worked, thank you! 

But after I construct the model, when I run onnx model checker, the output of simplify_model.py ie., pfe_sim.onnx fails the check with the following error.

```
onnx.checker.check_model(onnx_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.8/site-packages/onnx/checker.py", line 136, in check_model
    C.check_model(protobuf_string, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'onnx::Expand_21' of node: 
name: Tile_8 OpType: Tile
 is not output of any previous nodes.
 ```
 
`onnx::Expand_21` is the input to the Tile layer, which is the output of MaxPool. The checker says `onnx::Expand_21` is not an output of previous nodes, but it is the output of MaxPool layer. Would you know why the checker would fail?

Images attached show node properties for MaxPool and Tile as viewed on Netron
![maxpool_properties](https://github.com/CarkusL/CenterPoint/assets/76084774/01ee7071-2dcc-48ba-b001-c1e93302eafe)
![tile_properties](https://github.com/CarkusL/CenterPoint/assets/76084774/fc3f277b-c681-4648-9c90-d0c0e04ada60)

**Comment by rahul-dev-app** [comment]
Hi, I resolved the issue. I realized the `model.graph.node.append()` call in `reducemax_to_maxpool()` function was adding nodes the maxpool nodes at the end of onnx file. I used `insert()` instead of `append()` to insert the nodes at the right locations for topological structure to stay intact. 

Thank you!

**Comment by Byte247** [comment]
I have the same problem with a broken graph for pfe_sim.onnx. How did you get the input node name of the first Conv in L30?

**Comment by rahul-dev-app** [comment]
I checked the input name for the first Conv in the unsimplified pfe.onnx,
and changed the input.1 to that.
